### PR TITLE
Overhaul how point edit modes are enabled

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Move logic to enable point editing widgets into the respective views, purging it from `GroundControlPointsHelper`. This requires adding additional API's to the views, but allows us to eliminate the need to "lock out" editing registration points to edit ground control points (which was previously needed as there was no API to tell the `CameraView` to turn editing off).

### CODE REVIEW

**Comment by borovik135** [comment]
This does not compile on my ubuntu 20.04 system:
[ 34%] Generating qrc_appdata.cpp
Scanning dependencies of target TeleSculptor
[ 35%] Building CXX object gui/CMakeFiles/TeleSculptor.dir/TeleSculptor_autogen/mocs_compilation.cpp.o
In file included from /work/telesculptor/build/gui/TeleSculptor_autogen/EWIEGA46WW/moc_CameraView.cpp:9,
                 from /work/telesculptor/build/gui/TeleSculptor_autogen/mocs_compilation.cpp:5:
/work/telesculptor/src/gui/CameraView.h:34:10: fatal error: EditMode.h: No such file or directory
   34 | #include "EditMode.h"
      |          ^~~~~~~~~~~~
compilation terminated.

**Comment by mwoehlke-kitware** [comment]
Sorry! Please try again (updated this to include the missing file).

**Comment by borovik135** [comment]
OK, it works now, tnx!

File: gui/CameraView.cxx [hunk 1]
```diff
@@ -912,17 +911,16 @@ void CameraView::enableAntiAliasing(bool enable)
...
   QTE_D();
 
-  d->UI.actionPlaceEditCRP->setEnabled(state);
-
-  if (!state)
-  {
-    d->UI.actionPlaceEditCRP->setChecked(false);
-    d->registrationPointsWidget->enableWidget(false);
-  }
+  d->groundControlPointsWidget->enableWidget(
```
Comment (mleotta) [inline gui/CameraView.cxx:918]: out of curiosity, what would happen if we enabled both widgets at the same time?

File: gui/MainWindow.cxx [hunk 2]
```diff
@@ -261,6 +261,40 @@ class StateValue : public qtUiState::AbstractItem
   T data;
 };
 
+//-----------------------------------------------------------------------------
+class RecursionGuard
```
Comment (mleotta) [inline gui/MainWindow.cxx:265]: Should this utility be in a separate file?  It look reusable and we already have a **lot** of code in `MainWindow.cxx`

**Review by mleotta — APPROVED** [review]
Looks okay, but see suggestion about putting RecursionGuard and RecursionLock in a separate file.

File: gui/MainWindow.cxx (hunk 2 above)
Comment (mwoehlke-kitware) [reply gui/MainWindow.cxx:265]: Well, it should probably be in qtExtensions 🙂, but I didn't want to go to the effort.

**Review by mleotta — APPROVED** [review]
